Modify fzn2py to give error if no input is specified and to set the exit status if one of the piped commands fails.
This allows us to detect an invalid input etc.

diff --git a/fzn/fzn2py b/fzn/fzn2py
--- a/fzn/fzn2py
+++ b/fzn/fzn2py
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -e
 
 # translate flatzinc format to python/Numberjack 
 
@@ -12,6 +12,11 @@
 SED='sed -r'
 INPUT="$1"
 uname=$(uname)
+
+if [[ "$INPUT" == "" ]]; then
+    echo "Error: please specify an input fzn file."
+    exit 1
+fi
 
 pushd . > /dev/null
 SCRIPT_PATH="${BASH_SOURCE[0]}";
@@ -34,5 +39,11 @@ if [[ "$uname" == "Darwin" ]]; then
     fi
 fi
 
-# sed 's/;$//' $1 | sed -r 's/:: output_[a-zA-Z0-9_]+([(].*[)])*/::_output_/g' | sed -r 's/:: [a-zA-Z0-9_]+([(].*[)])*//g' | sed 's/^predicate .*$//' | sed 's/%.*$//' | sed 's/false/0/g' | sed 's/true/1/g' | sed -r 's/([-]*[0-9]+)[.][.]([-]*[0-9]+)/range(\1,1+\2)/g' | sed -r 's/([a-zA-Z0-9_]+)[[]([0-9+]+)[]]/\1[\2-1]/g' | awk -f ./fzn2py.awk | sed 's/{/[/g' | sed 's/}/]/g'
 $SED 's/;$//' $INPUT | $SED 's/:: output_/::_output_/g' | $SED 's/:: [a-zA-Z0-9_]+([(].*[)])*//g' | $SED 's/^predicate .*$//' | $SED 's/%.*$//' | $SED 's/false/0/g' | $SED 's/true/1/g' | $SED 's/([-]*[0-9]+)[.][.]([-]*[0-9]+)/range(\1,1+\2)/g' | $SED 's/([a-zA-Z0-9_]+)[[]([0-9+]+)[]]/\1[\2-1]/g' | gawk -f $MZNNJ_DIR/fzn2py.awk --assign MZNNJ_DIR=$MZNNJ_DIR | $SED 's/\{/\[/g' | $SED 's/\}/\]/g'
+
+# Check if any of the piped statements failed.
+for i in "${PIPESTATUS[@]}"; do
+    if [ "$i" != "0" ]; then
+        exit $i
+    fi
+done
